name: Data Analysis

on:
  push:
    branches:
      - main

jobs:
  data_analysis:
    runs-on: ubuntu-latest
    container:
      image: fallingstar10/hbsigrocker:latest

    steps:
    #- uses: actions/checkout@v2
     # with:
      #  persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
       # fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Fix ownership
      run: |
        sudo chown -R $(whoami) .

    #- name: Setup R
    #  uses: r-lib/actions/setup-r@v1

    #- name: Install dependencies
    #  run: |
    #    install.packages('quarto')

    - name: Render Rmarkdown
      run: |
        cd manuscript
        Rscript -e "library(knitr); knit('result.qmd')"
   
        

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
            # Artifact name
          name: result # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: manuscript/
          retention-days: 3 # optional
