name: Data Analysis

on:
  push:
    branches:
      - main

jobs:
  data_analysis:
    runs-on: ubuntu-latest
    container:
      image: fallingstar10/hbsigrocker:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Fix ownership
      run: |
        sudo chown -R $(whoami) .

    #- name: Setup R
    #  uses: r-lib/actions/setup-r@v1

    #- name: Install dependencies
    #  run: |
    #    install.packages('quarto')

    - name: Render Rmarkdown
      run: |
        cd manuscript
        Rscript -e "library(knitr); knit('result.qmd')"
        

    - name: Commit results
      run: |
        git config --global --add safe.directory /__w/Data_Analysis_in_GA/Data_Analysis_in_GA
        git config --global user.email "15860147513@163.com"
        git config --global user.name "rainoffallingstar"
        git add .
        git commit -m "Add analysis results" || echo "No changes to commit"
        git push https://${{ secrets.GH_TOKEN }}@github.com/rainoffallingstar/Data_Analysis_in_GA.git 
