name: Data Analysis

on:
  push:
    branches:
      - main

jobs:
  data_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

   # - name: Setup R
    #  uses: r-lib/actions/setup-r@v1

    - name: Install dependencies
      run: |
        touch 1.txt

    #- name: Render Rmarkdown
     # run: |
      #  cd manuscript
       # Rscript -e "library(knitr); knit('result.qmd')"
   
        

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
    	    name: result
    	    path: manuscript/result.md
    	    retention-days: 10 # <= 这里可以设置保留天数
