name: Data Analysis

on:
  push:
    branches:
      - main

jobs:
  data_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

   # - name: Setup R
    #  uses: r-lib/actions/setup-r@v1

    - name: Install dependencies
      run: |
        touch 1.txt

    #- name: Render Rmarkdown
     # run: |
      #  cd manuscript
       # Rscript -e "library(knitr); knit('result.qmd')"
   
        

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
            # Artifact name
          name: result # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: 1.txt
          retention-days: 10 # optional
